### ISSUE TITLE
Any possibility for functionality without a controller/with just a keyboard?

### ISSUE THREAD

**Issue by Kurtoid** [alex8b/gta5eyetracking#5]

**Comment by alex8b** [comment]
Hi!
It supports some of the features on keyboard as well:
F8 - Eye tracking settings menu
ARROWS - Navigate the eye tracking menu
B or XBUTTON1 - Shoot at gaze
J or XBUTTON2 - Incinerate at gaze
N or PGUP - Shoot a missile at gaze
H or PGDOWN - Tase at gaze
K - Debug info
